language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_script: 
 - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - composer install --dev -o -n
script: 
 - vendor/bin/phpunit
